package tpcreative.co.qrscanner.common

class ConstantKey {
    companion object {
        const val LAT = "lat"
        const val LON = "lon"
        const val QUERY = "query"
        const val FULL_NAME = "fullName"
        const val ADDRESS = "address"
        const val PHONE = "phone"
        const val MESSAGE = "message"
        const val EMAIL = "email"
        const val PRODUCT_ID = "productId"
        const val URL = "url"
        const val SSID = "ssId"
        const val PASSWORD = "password"
        const val NETWORK_ENCRYPTION = "networkEncryption"
        const val HIDDEN = "hidden"
        const val NOTE = "note"
        const val BIRTHDAY = "birthday"
        const val key_saved = "key_saved"
        const val key_logo_is_selected = "key_logo_is_selected"
        const val key_change_design_view = "key_change_design_view"
        const val key_change_design_save = "key_save_change_save"
        const val key_change_design_review = "key_save_change_review"
        const val key_change_design_logo = "key_save_change_logo"
        const val key_change_design_index = "key_change_design_index"

        const val TITLE  = "title"
        const val LOCATION = "location"
        const val DESCRIPTION = "description"
        const val START_EVENT_MILLISECONDS = "startEventMilliseconds"
        const val END_EVENT_MILLISECONDS = "endEventMilliseconds"
        const val ISBN = "ISBN"
        const val TEXT = "text"
        const val SUBJECT = "subject"
        const val CONTENT = "content"
        const val BARCODE_FORMAT = "barcode_format"
        const val CREATED_DATETIME = "created_datetime"
        const val FIRST_NAME = "first_name"
        const val LAST_NAME = "last_name"
        const val MIDDLE_NAME = "middle_name"
        const val SUFFIX_NAME = "suffix_name"
        const val GooglePlayPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxToUe5+7Xy+Q7YYZfuMofqZmNe0021vMBJ32VQVPa8+Hd0z9YWPWTVvplslRX4rKU2TQ1l93yMzPVIHVxLIwPuo9OC9I8sO7LpOi91pyPk9fT0IjVaWDTSv1h/qLUE6m3OS5/LVPYQNbHCp3yqujSmj6bIj7AvbjhF36XjxZaESfJI3KhtXy/RD+ZaM255TgY6g1vwN3ObsrXZ3e98VrT8ehJrry8u8RTpiZ6NWTgcsk/riMPYZiwebf6fUHQgidAtwdBfZx94hYgldt5kPN3hB2LcG4KVj9jI2QY9Y4WsOPQ643I9fP8e9VbYW8/uAOTZnvUeUW9qb9qIw3NHyV6wIDAQAB"
        const val GooglePlayInnovationPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAydYUtiWkErix8KwcB1BrbCZp4cTZvbHU/biXcD/uWZ1Tq6TJuSH8byw7pv/SCb6zgatXzxHNQn/rj0qS9BGsVswpgz68rzD24tQFCDnlasY6GUp4FXJ7/8n261a5U9nylTdIp4AqGDb1mqWEMZKPfTRti6qjP+W2ozNGh4XyJJQAfWYrhYPLdKb8RFllGJWhxkj4BRVqeDAPoDoacp3Z3lRFuDjciNCSnEFtLt6Dkj76C+nsignOVD7HsK6s8xnBvGjQYtEHuIFMOtEuS4R3hGEvFVGjXaWRlaJBZgZDywD7AMUIVOhzk66Vh8eKvp2hMAWgO+5qqPZfGOZGwe6BpQIDAQAB"
        const val GooglePlaySuperInnovationPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjWPILJylpbFwDiZpTjca0RwnlkRGVKwzbJ6IpHWZMQuX8MDARn4U4AVPJe2NU04LkKX++bSFl436Qve4VoXAJ3G8tvu4q++2ZVEBnlONXrhzC7hpWylhtannADiXMs+YrzNuZ694NQhfo3YiiSey6Tz0raA4KZUywLdL6uu7bVk0+ozkHzFCHHXgmIXK0bqQousTP+RQyl41/G3hzl4TocMSW2gm4Ytpa2eDows0azOUdgmaGcZhdPA22dPqUo34uSE8nD637eFFyZX4pdD4r5fScKu2IXVRWe2Mats0nkyj5GzHOBUz+8ratj+hquH4SUXUyq+Vksq5tT+pdPxnwwIDAQAB"
    }
}