package tpcreative.co.qrscanner.model

enum class EnumAction {
    SAVE, SHARE, PRINT, CLIPBOARD, SEARCH, BARCODE, Other,PHONE_CALL,URL_ADDRESS_BOOK,PHONE_ADDRESS_BOOK,EMAIL_ADDRESS_BOOK,GEO_ADDRESS_BOOK,EMAIL,DO_ADVANCE,DO_BASIC,TAKE_NOTE,MARK_FAVORITE,VIEW_CODE,NONE
}