package tpcreative.co.qrscanner.model

enum class EnumAction {
    SAVE, SHARE, PRINT, CLIPBOARD,SEARCH, SEARCH_WEB,SEARCH_AMAZON,SEARCH_EBAY, BARCODE, Other,PHONE_CALL,URL_ADDRESS_BOOK,PHONE_ADDRESS_BOOK,EMAIL_ADDRESS_BOOK,GEO_ADDRESS_BOOK,EMAIL,DO_ADVANCE,DO_BASIC,TAKE_NOTE,MARK_FAVORITE,VIEW_CODE,VIEW_FILE,VIEW_CROP,SUPPORTED_CODES,TIPS_SCANNING,GUIDES_VIDEO,SEND_US_AN_EMAIL,QRCODE,EAN_5,CODE_25,NONE
}