package tpcreative.co.qrscanner.model

enum class EnumPositionMarker {
    DEFAULT,CORNER_10PX,CORNER_25PX,CIRCLE,CORNER_TOP_RIGHT_BOTTOM_LEFT,CORNER_TOP_LEFT_BOTTOM_RIGHT,CORNER_TOP_LEFT_TOP_RIGHT_BOTTOM_LEFT
}